<div class="products">
    <?php foreach ($products as $product) : ?>
        <div class="product">
            <img src="<?= url('../../asset/img/products/' . $product['img']) ?>" alt="img" width="100px" height="100px">

            <h3><?= $product['name'] ?></h3>
            <p><?= $product['description'] ?></p>
            <p class="price">  <?= $product['price'] ?> € </p>
            <a href="<?= url('/product/edit/' . $product['id']) ?>">edit</a>
            <a href="<?= url('/product/show?id=' . $product['id']) ?>">Voir le produit</a>
        </div>
    <?php endforeach; ?>

</div>



