<p>Product show</p>


    <?= $product['name'] ?>
    <?= $product['id'] ?>
    <img src="<?= url('../../asset/img/products/' . $product['img']) ?>" alt="img" width="50px" height="50px">
    <?= $product['description'] ?>
    <p>  <?= $product['price'] ?> € </p>



    <a href="<?= url('/') ?>">retourn</a>

    <form method="POST">
        <input type="submit" value="submit" name="submit">
    </form>
