<div class="product-show">
    <img src="<?= url('../../asset/img/products/' . $product['img']) ?>" alt="img" width="200px" height="200px">

    <h2><?= $product['name'] ?></h2>
    <p><?= $product['description'] ?></p>
    <p class="price"> PRIX :  <?= $product['price'] ?> € </p>

    <div class="btn-space">
        <form method="POST">
			<?php if (!auth()->isAuthenticated()): ?>
                <a href="<?= url('/signUp') ?> " class="link">Tu le veux ? alors connecte toi  </a>
                <?php else: ?>
                <input type="submit" value="Je le veux !" name="submit" class="link">
			<?php endif; ?>
        </form>
        <a href="<?= url('/') ?>" class="link">retourn</a>
        <?php if (auth()->isAdmin()): ?>
            <a href="<?= url('/product/delete?id=' . $product['id']) ?>" class="link">Supprimer le produit</a>
            <a href="<?= url('/edit?id=' .$product['id']) ?>" class="link">Edit</a>
		<?php endif; ?>
    </div>


</div>





