<div class="user-connect">
    <h2>SE CONNECTER </h2>

    <!--  if Errors from basket-->

        <?php if (flashBag()->has('basketError')): ?>
            <div class="errors">
                <div class="error-header">
                    <div class="like-btn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
                <p class="error"><?= flashBag()->get('basketError') ?></p>
            </div>
        <?php endif; ?>

    <form method="POST" action="<?= url('/user/auth') ?>" class="user-form">

        <div class="input-box">
            <input type="text" name="email" placeholder="email" class="input">
            <i class="fa-solid fa-at"></i>
        </div>
        <!-- if Errors -->

            <?php if (flashBag()->has('email')): ?>
                <div class="errors">
                    <div class="error-header">
                        <div class="like-btn">
                            <i class="fa-solid fa-xmark"></i>
                        </div>
                    </div>
                    <p class="error"> <?= flashBag()->get('email') ?></p>
                </div>
            <?php endif; ?>


        <div class="input-box">
            <input type="password" name="password" placeholder="mot de passe" class="password input">
            <i class="fa-solid fa-eye"></i>
        </div>

        <!-- if Errors -->

            <?php if (flashBag()->has('password')): ?>
                <div class="errors">
                    <div class="error-header">
                        <div class="like-btn">
                            <i class="fa-solid fa-xmark"></i>
                        </div>
                    </div>
                <p class="error"><?= flashBag()->get('password') ?></p>
            </div>
            <?php endif; ?>


        <button type="submit" class="link">Se connecter</button>
    </form>
    <div class="not-yet-sign-up">
        <p>Pas encore inscrit ? </p>
        <a href="<?= url('/signUp') ?>" class="link">Créer un compte</a></p>
    </div>
</div>
