<div class="user-profile">
    <h2>Mon profil :</h2>

    <?php if ($user['firstName']):?>
        <p>Hello <?= htmlentities($user['firstName']) ?></p>
    <?php else: ?>
        <p>Et si on complete le profile ? <?= htmlentities($user['email']) ?></p>
        <a href="<?= url('/edit') ?>">Complete your profile</a>
    <?php endif; ?>

    <form action="<?= url('/user/edit') ?>" method="post" class="user-profile-edit">
        <!-- Info -->
            <input type="text" name="firstName" value="<?= htmlentities($user['firstName'] ?? 'Prénom') ?>" class="input" />
            <input type="text" name="lastName" value="<?= htmlentities($user['lastName'] ?? 'Nom') ?>" class="input" />
            <input type="text" name="email" value="<?= htmlentities($user['email'] ?? 'Email') ?>" class="input"/>
        <!--  if Errors -->
        <div class="error">
			<?php if (flashBag()->has('email')): ?>
                <p class="errors"><?= flashBag()->get('email') ?></p>
			<?php endif; ?>
        </div>

        <!-- ADRESSE -->

        <input type="text" name="address" value="<?= htmlentities($user['address'] ?? 'Adresse') ?>" class="input"/>
        <input type="text" name="city" value="<?= htmlentities($user['city'] ?? 'Ville') ?>" class="input">
        <input type="text" name="codePostal" value="<?= htmlentities($user['codePostal'] ?? '33 000') ?>" class="input">
        <button type="submit" class="link">Modifier mes infos</button>
    </form>
    <!-- PASSWORD -->
    <p>Mode de passe :</p>
    <form action="<?= url('/user/editPassword') ?>" method="post">
        <!--  old pwd -->
        <input type="password" name="passwordOld"  placeholder="Ancien mode de passe" class="input"/>
        <!--  new pwd -->
        <input type="password" name="newPassword" placeholder="Nouveau mode de passe" class="input"/>
        <!--  if Errors -->
        <?php if (flashBag()->has('password')): ?>
            <p class="error"><?= flashBag()->get('password') ?></p>
        <?php endif; ?>
        <button type="submit" class="link">Modifier mon mdp</button>
    </form>
    <!-- DELETE  -->
    <div class="delete-container">
        <p>Supprime Mon Compte</p>
        <form action="<?= url('/user/delete') ?>" method="post">
            <label for="delete">Vraiment ?  </label>
            <input type="checkbox" name="delete" class="delete-user">
            <button type="submit" class="link delete">Sayonara</button>
            <?php if (flashBag()->has('delete')): ?>
                <p class="errors"><?= flashBag()->get('delete') ?></p>
            <?php endif; ?>
        </form>
    </div>
</div>