<div class="user-connect">
    <h2>CREÉR UN COMPTE </h2>

    <form method="POST" action="<?= url('/user/store') ?>" class="user-form">

        <div class="input-box">
            <input type="text" name="email" placeholder="email" class="input">
            <i class="fa-solid fa-at"></i>
        </div>
        <!--  if Errors -->
        <div class="errors">
            <?php if (flashBag()->has('email')): ?>
                    <p class="error"><?= flashBag()->get('email') ?></p>
            <?php endif; ?>
        </div>

        <div class="input-box">
            <input type="password" name="password" placeholder="mot de passe" class="password input">
            <i class="fa-solid fa-eye"></i>
        </div>
        <!-- if Errors -->
        <div class="errors">
            <?php if (flashBag()->has('password')): ?>
                <p class="error"><?= flashBag()->get('password') ?></p>
            <?php endif; ?>
        </div>

        <button type="submit" class="link">Creé mon compte</button>
    </form>
</div>