<div class="user-connect">
    <h2>CREÉR UN COMPTE </h2>

    <form method="POST" action="<?= url('/user/store') ?>" class="user-form">

        <div class="input-box">
            <input type="text" name="email" placeholder="email" class="input">
            <i class="fa-solid fa-at"></i>
        </div>
        <!--  if Errors -->

            <?php if (flashBag()->has('email')): ?>
            <div class="errors">
                <div class="error-header">
                    <div class="like-btn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
                    <p class="error"><?= flashBag()->get('email') ?></p>
            </div>
            <?php endif; ?>


        <div class="input-box">
            <input type="password" name="password" placeholder="mot de passe" class="password input">
            <i class="fa-solid fa-eye"></i>
        </div>
        <!-- if Errors -->

            <?php if (flashBag()->has('password')): ?>
            <div class="errors">
                <div class="error-header">
                    <div class="like-btn">
                        <i class="fa-solid fa-xmark"></i>
                    </div>
                </div>
                <p class="error"><?= flashBag()->get('password') ?></p>
            </div>
            <?php endif; ?>


        <button type="submit" class="link">Creé mon compte</button>
        <p>Déjà inscrit ? </p>
        <a href="<?= url('/logIn') ?>" class="link">Se connecter</a></p>
    </form>
</div>